- name: Send cluster Status via Slack notification
      community.general.slack:
        token: "{{ lookup('env','SLACK_TOKEN') }}"
        msg: |
            ### Cluster Installation ###
            --------------------------------------
            `Status`: Success.
            `Cluster`: http://{{ ocp_ingress_domain[0] }}
            --------------------------------------
        channel: "{{ lookup('env','SLACK_CHANNEL') }}"
        color: good
        username: "Ansible on {{ inventory_hostname }}"
        icon_url: ''
        link_names: 0
        parse: 'none'
