---
- name: Notify Cluster Preinstall
  hosts: all
  gather_facts: false

  tasks: 
   - name: Send cluster status via Slack notification
     community.general.slack:
        token: T04PZ1GM0PM/B04U906ERK5/T6A9pFYJjz67LyNqroQDehmA
        msg: |
            ### Cluster creation ###
            --------------------------------------
            `Status`: Success.
            `Cluster`: Cluster provisionig started. 
            --------------------------------------
        channel: '#rhacm-demo'
        color: good
        username: "Ansible on {{ inventory_hostname }}"
        icon_url: ''
        link_names: 0
        parse: 'none'
